spawn:
     x: 10
     y: 10
     z: 10
pitch:
     center:
          x: -30
          y: 66
          z: -57
     quaffle:
          x: -30
          y: 66
          z: -57
     snitch:
          x: -30
          y: 66
          z: -54
     first:
          x: -13
          y: 66
          z: -58
     second:
          x: -46
          y: 66
          z: -57
net:
     l_1:
          x: 1
          y: 2
          z: 3
          team: home
     l_2:
          x: 4
          y: 5
          z: 6
          team: away
